// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmithASP.Models;

namespace SmithASP.Migrations
{
    [DbContext(typeof(CryptogramDbContext))]
    [Migration("20190719200219_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmithASP.Models.Cryptogram", b =>
                {
                    b.Property<int>("CryptogramId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("key")
                        .IsRequired();

                    b.Property<string>("message")
                        .IsRequired();

                    b.Property<string>("result")
                        .IsRequired();

                    b.HasKey("CryptogramId");

                    b.ToTable("Cryptograms");
                });

            modelBuilder.Entity("SmithASP.Models.CryptogramEncryptionMethods", b =>
                {
                    b.Property<int>("CryptogramId");

                    b.Property<int>("EncryptionMethodId");

                    b.HasKey("CryptogramId", "EncryptionMethodId");

                    b.ToTable("CryptogramEncryptionMethods");
                });

            modelBuilder.Entity("SmithASP.Models.EncryptionMethods", b =>
                {
                    b.Property<int>("EncryptionMethodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("EncryptionMethodId");

                    b.ToTable("EncryptionMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
