// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmithASP.Models.DbContexts;

namespace SmithASP.Migrations.Circuit
{
    [DbContext(typeof(CircuitContext))]
    [Migration("20190905170907_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmithASP.Models.Electronics.Circuit", b =>
                {
                    b.Property<int>("CircuitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComponentCount");

                    b.Property<int?>("CurrentId");

                    b.Property<double>("ElectronsPerSecond");

                    b.Property<double>("JoulesPerSecond");

                    b.Property<double>("RunTime");

                    b.Property<int?>("SourceVoltsVoltageId");

                    b.Property<int?>("TotalResistanceResistanceId");

                    b.HasKey("CircuitId");

                    b.HasIndex("CurrentId");

                    b.HasIndex("SourceVoltsVoltageId");

                    b.HasIndex("TotalResistanceResistanceId");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("SmithASP.Models.Electronics.Current", b =>
                {
                    b.Property<int>("CurrentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amps");

                    b.HasKey("CurrentId");

                    b.ToTable("Current");
                });

            modelBuilder.Entity("SmithASP.Models.Electronics.Resistance", b =>
                {
                    b.Property<int>("ResistanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CircuitId");

                    b.Property<double>("Ohms");

                    b.HasKey("ResistanceId");

                    b.HasIndex("CircuitId");

                    b.ToTable("Resistance");
                });

            modelBuilder.Entity("SmithASP.Models.Electronics.Voltage", b =>
                {
                    b.Property<int>("VoltageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Volts");

                    b.HasKey("VoltageId");

                    b.ToTable("Voltage");
                });

            modelBuilder.Entity("SmithASP.Models.Electronics.Circuit", b =>
                {
                    b.HasOne("SmithASP.Models.Electronics.Current", "Current")
                        .WithMany()
                        .HasForeignKey("CurrentId");

                    b.HasOne("SmithASP.Models.Electronics.Voltage", "SourceVolts")
                        .WithMany()
                        .HasForeignKey("SourceVoltsVoltageId");

                    b.HasOne("SmithASP.Models.Electronics.Resistance", "TotalResistance")
                        .WithMany()
                        .HasForeignKey("TotalResistanceResistanceId");
                });

            modelBuilder.Entity("SmithASP.Models.Electronics.Resistance", b =>
                {
                    b.HasOne("SmithASP.Models.Electronics.Circuit")
                        .WithMany("ResistorsList")
                        .HasForeignKey("CircuitId");
                });
#pragma warning restore 612, 618
        }
    }
}
